// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/proto/connector/connector.proto

package connector

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectsRequest) Reset() {
	*x = GetProjectsRequest{}
	mi := &file_internal_proto_connector_connector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectsRequest) ProtoMessage() {}

func (x *GetProjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_connector_connector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectsRequest.ProtoReflect.Descriptor instead.
func (*GetProjectsRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_connector_connector_proto_rawDescGZIP(), []int{0}
}

func (x *GetProjectsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetProjectsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetProjectsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type GetProjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projects      []*ProjectDTO          `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	PageInfo      *PageInfo              `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectsResponse) Reset() {
	*x = GetProjectsResponse{}
	mi := &file_internal_proto_connector_connector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectsResponse) ProtoMessage() {}

func (x *GetProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_connector_connector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectsResponse.ProtoReflect.Descriptor instead.
func (*GetProjectsResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_connector_connector_proto_rawDescGZIP(), []int{1}
}

func (x *GetProjectsResponse) GetProjects() []*ProjectDTO {
	if x != nil {
		return x.Projects
	}
	return nil
}

func (x *GetProjectsResponse) GetPageInfo() *PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

type ProjectDTO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectDTO) Reset() {
	*x = ProjectDTO{}
	mi := &file_internal_proto_connector_connector_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectDTO) ProtoMessage() {}

func (x *ProjectDTO) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_connector_connector_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectDTO.ProtoReflect.Descriptor instead.
func (*ProjectDTO) Descriptor() ([]byte, []int) {
	return file_internal_proto_connector_connector_proto_rawDescGZIP(), []int{2}
}

func (x *ProjectDTO) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ProjectDTO) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProjectDTO) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type PageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentPage   int32                  `protobuf:"varint,1,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	ProjectsCount int32                  `protobuf:"varint,2,opt,name=projects_count,json=projectsCount,proto3" json:"projects_count,omitempty"`
	TotalPages    int32                  `protobuf:"varint,3,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageInfo) Reset() {
	*x = PageInfo{}
	mi := &file_internal_proto_connector_connector_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageInfo) ProtoMessage() {}

func (x *PageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_connector_connector_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageInfo.ProtoReflect.Descriptor instead.
func (*PageInfo) Descriptor() ([]byte, []int) {
	return file_internal_proto_connector_connector_proto_rawDescGZIP(), []int{3}
}

func (x *PageInfo) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *PageInfo) GetProjectsCount() int32 {
	if x != nil {
		return x.ProjectsCount
	}
	return 0
}

func (x *PageInfo) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type UpdateProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectKey    string                 `protobuf:"bytes,1,opt,name=project_key,json=projectKey,proto3" json:"project_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProjectRequest) Reset() {
	*x = UpdateProjectRequest{}
	mi := &file_internal_proto_connector_connector_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProjectRequest) ProtoMessage() {}

func (x *UpdateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_connector_connector_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProjectRequest.ProtoReflect.Descriptor instead.
func (*UpdateProjectRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_connector_connector_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateProjectRequest) GetProjectKey() string {
	if x != nil {
		return x.ProjectKey
	}
	return ""
}

type UpdateProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Project       string                 `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProjectResponse) Reset() {
	*x = UpdateProjectResponse{}
	mi := &file_internal_proto_connector_connector_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProjectResponse) ProtoMessage() {}

func (x *UpdateProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_connector_connector_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProjectResponse.ProtoReflect.Descriptor instead.
func (*UpdateProjectResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_connector_connector_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateProjectResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateProjectResponse) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

type DeleteProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     int64                  `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProjectRequest) Reset() {
	*x = DeleteProjectRequest{}
	mi := &file_internal_proto_connector_connector_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProjectRequest) ProtoMessage() {}

func (x *DeleteProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_connector_connector_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProjectRequest.ProtoReflect.Descriptor instead.
func (*DeleteProjectRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_connector_connector_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteProjectRequest) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

type DeleteProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProjectResponse) Reset() {
	*x = DeleteProjectResponse{}
	mi := &file_internal_proto_connector_connector_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProjectResponse) ProtoMessage() {}

func (x *DeleteProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_connector_connector_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProjectResponse.ProtoReflect.Descriptor instead.
func (*DeleteProjectResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_connector_connector_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteProjectResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_internal_proto_connector_connector_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_connector_connector_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_connector_connector_proto_rawDescGZIP(), []int{8}
}

type HealthResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MasterUp          bool                   `protobuf:"varint,1,opt,name=master_up,json=masterUp,proto3" json:"master_up,omitempty"`
	ReplicaUp         bool                   `protobuf:"varint,2,opt,name=replica_up,json=replicaUp,proto3" json:"replica_up,omitempty"`
	MasterInRecovery  bool                   `protobuf:"varint,3,opt,name=master_in_recovery,json=masterInRecovery,proto3" json:"master_in_recovery,omitempty"`
	ReplicaInRecovery bool                   `protobuf:"varint,4,opt,name=replica_in_recovery,json=replicaInRecovery,proto3" json:"replica_in_recovery,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_internal_proto_connector_connector_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_connector_connector_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_connector_connector_proto_rawDescGZIP(), []int{9}
}

func (x *HealthResponse) GetMasterUp() bool {
	if x != nil {
		return x.MasterUp
	}
	return false
}

func (x *HealthResponse) GetReplicaUp() bool {
	if x != nil {
		return x.ReplicaUp
	}
	return false
}

func (x *HealthResponse) GetMasterInRecovery() bool {
	if x != nil {
		return x.MasterInRecovery
	}
	return false
}

func (x *HealthResponse) GetReplicaInRecovery() bool {
	if x != nil {
		return x.ReplicaInRecovery
	}
	return false
}

var File_internal_proto_connector_connector_proto protoreflect.FileDescriptor

const file_internal_proto_connector_connector_proto_rawDesc = "" +
	"\n" +
	"(internal/proto/connector/connector.proto\x12\tconnector\"V\n" +
	"\x12GetProjectsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\"z\n" +
	"\x13GetProjectsResponse\x121\n" +
	"\bprojects\x18\x01 \x03(\v2\x15.connector.ProjectDTOR\bprojects\x120\n" +
	"\tpage_info\x18\x02 \x01(\v2\x13.connector.PageInfoR\bpageInfo\"D\n" +
	"\n" +
	"ProjectDTO\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\"u\n" +
	"\bPageInfo\x12!\n" +
	"\fcurrent_page\x18\x01 \x01(\x05R\vcurrentPage\x12%\n" +
	"\x0eprojects_count\x18\x02 \x01(\x05R\rprojectsCount\x12\x1f\n" +
	"\vtotal_pages\x18\x03 \x01(\x05R\n" +
	"totalPages\"7\n" +
	"\x14UpdateProjectRequest\x12\x1f\n" +
	"\vproject_key\x18\x01 \x01(\tR\n" +
	"projectKey\"I\n" +
	"\x15UpdateProjectResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aproject\x18\x02 \x01(\tR\aproject\"5\n" +
	"\x14DeleteProjectRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\x03R\tprojectId\"/\n" +
	"\x15DeleteProjectResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x0f\n" +
	"\rHealthRequest\"\xaa\x01\n" +
	"\x0eHealthResponse\x12\x1b\n" +
	"\tmaster_up\x18\x01 \x01(\bR\bmasterUp\x12\x1d\n" +
	"\n" +
	"replica_up\x18\x02 \x01(\bR\treplicaUp\x12,\n" +
	"\x12master_in_recovery\x18\x03 \x01(\bR\x10masterInRecovery\x12.\n" +
	"\x13replica_in_recovery\x18\x04 \x01(\bR\x11replicaInRecovery2\xc7\x02\n" +
	"\x10ConnectorService\x12L\n" +
	"\vGetProjects\x12\x1d.connector.GetProjectsRequest\x1a\x1e.connector.GetProjectsResponse\x12R\n" +
	"\rUpdateProject\x12\x1f.connector.UpdateProjectRequest\x1a .connector.UpdateProjectResponse\x12R\n" +
	"\rDeleteProject\x12\x1f.connector.DeleteProjectRequest\x1a .connector.DeleteProjectResponse\x12=\n" +
	"\x06Health\x12\x18.connector.HealthRequest\x1a\x19.connector.HealthResponseB2Z0hse-2026-golang-project/internal/proto/connectorb\x06proto3"

var (
	file_internal_proto_connector_connector_proto_rawDescOnce sync.Once
	file_internal_proto_connector_connector_proto_rawDescData []byte
)

func file_internal_proto_connector_connector_proto_rawDescGZIP() []byte {
	file_internal_proto_connector_connector_proto_rawDescOnce.Do(func() {
		file_internal_proto_connector_connector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_connector_connector_proto_rawDesc), len(file_internal_proto_connector_connector_proto_rawDesc)))
	})
	return file_internal_proto_connector_connector_proto_rawDescData
}

var file_internal_proto_connector_connector_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_internal_proto_connector_connector_proto_goTypes = []any{
	(*GetProjectsRequest)(nil),    // 0: connector.GetProjectsRequest
	(*GetProjectsResponse)(nil),   // 1: connector.GetProjectsResponse
	(*ProjectDTO)(nil),            // 2: connector.ProjectDTO
	(*PageInfo)(nil),              // 3: connector.PageInfo
	(*UpdateProjectRequest)(nil),  // 4: connector.UpdateProjectRequest
	(*UpdateProjectResponse)(nil), // 5: connector.UpdateProjectResponse
	(*DeleteProjectRequest)(nil),  // 6: connector.DeleteProjectRequest
	(*DeleteProjectResponse)(nil), // 7: connector.DeleteProjectResponse
	(*HealthRequest)(nil),         // 8: connector.HealthRequest
	(*HealthResponse)(nil),        // 9: connector.HealthResponse
}
var file_internal_proto_connector_connector_proto_depIdxs = []int32{
	2, // 0: connector.GetProjectsResponse.projects:type_name -> connector.ProjectDTO
	3, // 1: connector.GetProjectsResponse.page_info:type_name -> connector.PageInfo
	0, // 2: connector.ConnectorService.GetProjects:input_type -> connector.GetProjectsRequest
	4, // 3: connector.ConnectorService.UpdateProject:input_type -> connector.UpdateProjectRequest
	6, // 4: connector.ConnectorService.DeleteProject:input_type -> connector.DeleteProjectRequest
	8, // 5: connector.ConnectorService.Health:input_type -> connector.HealthRequest
	1, // 6: connector.ConnectorService.GetProjects:output_type -> connector.GetProjectsResponse
	5, // 7: connector.ConnectorService.UpdateProject:output_type -> connector.UpdateProjectResponse
	7, // 8: connector.ConnectorService.DeleteProject:output_type -> connector.DeleteProjectResponse
	9, // 9: connector.ConnectorService.Health:output_type -> connector.HealthResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_proto_connector_connector_proto_init() }
func file_internal_proto_connector_connector_proto_init() {
	if File_internal_proto_connector_connector_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_connector_connector_proto_rawDesc), len(file_internal_proto_connector_connector_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_connector_connector_proto_goTypes,
		DependencyIndexes: file_internal_proto_connector_connector_proto_depIdxs,
		MessageInfos:      file_internal_proto_connector_connector_proto_msgTypes,
	}.Build()
	File_internal_proto_connector_connector_proto = out.File
	file_internal_proto_connector_connector_proto_goTypes = nil
	file_internal_proto_connector_connector_proto_depIdxs = nil
}
